# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\pyqt\09\vehiclerentaldlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VehicleRentalDlg(object):
    def setupUi(self, VehicleRentalDlg):
        VehicleRentalDlg.setObjectName(_fromUtf8("VehicleRentalDlg"))
        VehicleRentalDlg.resize(206, 246)
        self.gridLayout = QtGui.QGridLayout(VehicleRentalDlg)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(VehicleRentalDlg)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.vehicleComboBox = QtGui.QComboBox(VehicleRentalDlg)
        self.vehicleComboBox.setObjectName(_fromUtf8("vehicleComboBox"))
        self.vehicleComboBox.addItem(_fromUtf8(""))
        self.vehicleComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.vehicleComboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(VehicleRentalDlg)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.colorComboBox = QtGui.QComboBox(self.page_2)
        self.colorComboBox.setObjectName(_fromUtf8("colorComboBox"))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.colorComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.colorComboBox, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.seatsSpinBox = QtGui.QSpinBox(self.page_2)
        self.seatsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seatsSpinBox.setMinimum(2)
        self.seatsSpinBox.setMaximum(12)
        self.seatsSpinBox.setProperty("value", 4)
        self.seatsSpinBox.setObjectName(_fromUtf8("seatsSpinBox"))
        self.gridLayout_3.addWidget(self.seatsSpinBox, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.weightSpinBox = QtGui.QSpinBox(self.page)
        self.weightSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightSpinBox.setMinimum(1)
        self.weightSpinBox.setMaximum(8)
        self.weightSpinBox.setProperty("value", 1)
        self.weightSpinBox.setObjectName(_fromUtf8("weightSpinBox"))
        self.gridLayout_2.addWidget(self.weightSpinBox, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.volumeSpinBox = QtGui.QSpinBox(self.page)
        self.volumeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volumeSpinBox.setMinimum(4)
        self.volumeSpinBox.setMaximum(22)
        self.volumeSpinBox.setProperty("value", 10)
        self.volumeSpinBox.setObjectName(_fromUtf8("volumeSpinBox"))
        self.gridLayout_2.addWidget(self.volumeSpinBox, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(VehicleRentalDlg)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.mileageLabel = QtGui.QLabel(VehicleRentalDlg)
        self.mileageLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mileageLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.mileageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mileageLabel.setWordWrap(False)
        self.mileageLabel.setObjectName(_fromUtf8("mileageLabel"))
        self.horizontalLayout_2.addWidget(self.mileageLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(185, 68, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(VehicleRentalDlg)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.label.setBuddy(self.vehicleComboBox)
        self.label_4.setBuddy(self.colorComboBox)
        self.label_5.setBuddy(self.seatsSpinBox)
        self.label_2.setBuddy(self.weightSpinBox)
        self.label_3.setBuddy(self.volumeSpinBox)

        self.retranslateUi(VehicleRentalDlg)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), VehicleRentalDlg.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), VehicleRentalDlg.reject)
        QtCore.QObject.connect(self.vehicleComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(VehicleRentalDlg)

    def retranslateUi(self, VehicleRentalDlg):
        VehicleRentalDlg.setWindowTitle(_translate("VehicleRentalDlg", "Vehicle Renta", None))
        self.label.setText(_translate("VehicleRentalDlg", "&Vehicle Type:", None))
        self.vehicleComboBox.setItemText(0, _translate("VehicleRentalDlg", "Car", None))
        self.vehicleComboBox.setItemText(1, _translate("VehicleRentalDlg", "Van", None))
        self.label_4.setText(_translate("VehicleRentalDlg", "Co&lor:", None))
        self.colorComboBox.setItemText(0, _translate("VehicleRentalDlg", "Black", None))
        self.colorComboBox.setItemText(1, _translate("VehicleRentalDlg", "Blue", None))
        self.colorComboBox.setItemText(2, _translate("VehicleRentalDlg", "Green", None))
        self.colorComboBox.setItemText(3, _translate("VehicleRentalDlg", "Red", None))
        self.colorComboBox.setItemText(4, _translate("VehicleRentalDlg", "Silver", None))
        self.colorComboBox.setItemText(5, _translate("VehicleRentalDlg", "White", None))
        self.colorComboBox.setItemText(6, _translate("VehicleRentalDlg", "Yellow", None))
        self.label_5.setText(_translate("VehicleRentalDlg", "&Seats:", None))
        self.label_2.setText(_translate("VehicleRentalDlg", "&Weight:", None))
        self.weightSpinBox.setSuffix(_translate("VehicleRentalDlg", "tons", None))
        self.label_3.setText(_translate("VehicleRentalDlg", "Volu&me:", None))
        self.volumeSpinBox.setSuffix(_translate("VehicleRentalDlg", " cu m", None))
        self.label_6.setText(_translate("VehicleRentalDlg", "Max. Mileage:", None))
        self.mileageLabel.setText(_translate("VehicleRentalDlg", "1000 miles", None))

